server:
  address: 0.0.0.0
  port: 8886

spring:
  thymeleaf:
    prefix: classpath:/templates/
#  freemarker:
#    suffix: .html
  datasource:
    url: jdbc:mysql://120.79.204.188:3306/mylove?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mylove
    password: mylove

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: LOWER_CASE
    default-property-inclusion: NON_NULL